[package]
name = "nyarray"
version = "0.2.0"
edition = "2024"
description = "stack-allocated vector type"
repository = "https://github.com/wainggan/nyarray.git"
readme = "readme.md"
license = "Apache-2.0"

[features]
default = ["std"]
std = []

[dependencies]

